Traceback (most recent call last):
  File "/home/shrey/.conda/envs/jupyterbook/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/shrey/.conda/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/shrey/.conda/envs/jupyterbook/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/shrey/.conda/envs/jupyterbook/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/shrey/.conda/envs/jupyterbook/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/shrey/.conda/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/shrey/.conda/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/shrey/.conda/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from IPython.display import Image, display
import datetime as dt
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.patches import Patch
import numpy as np
import plotly.express as px
import plotly.figure_factory as ff

figure(figsize=(10,12), dpi=80)
df = [dict(Task="Third Year Review", Start='2022-11-01', Finish='2022-12-01'),
      dict(Task="HPC IO tuner", Start='2022-07-10', Finish='2022-07-30'),
      dict(Task="SC deadline", Start='2022-08-1', Finish='2022-08-10'),
      dict(Task="Threads utilisation", Start='2022-07-25', Finish='2022-07-30'),
      dict(Task="Add fenicsX", Start='2022-07-25', Finish='2022-07-30'),
      dict(Task="SC deadline", Start='2022-08-1', Finish='2022-08-10'),
      dict(Task="Second Year Review", Start='2021-11-01', Finish='2021-12-01'),
      dict(Task="CIUK 21", Start='2021-10-01', Finish='2021-11-01'),
      dict(Task="First Year Review", Start='2021-1-01', Finish='2021-2-01')]

fig = ff.create_gantt(df)
fig.show()


------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 10>[0;34m()[0m
[1;32m      7[0m [38;5;28;01mimport[39;00m [38;5;21;01mplotly[39;00m[38;5;21;01m.[39;00m[38;5;21;01mexpress[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpx[39;00m
[1;32m      8[0m [38;5;28;01mimport[39;00m [38;5;21;01mplotly[39;00m[38;5;21;01m.[39;00m[38;5;21;01mfigure_factory[39;00m [38;5;28;01mas[39;00m [38;5;21;01mff[39;00m
[0;32m---> 10[0m [43mfigure[49m(figsize[38;5;241m=[39m([38;5;241m10[39m,[38;5;241m12[39m), dpi[38;5;241m=[39m[38;5;241m80[39m)
[1;32m     11[0m df [38;5;241m=[39m [[38;5;28mdict[39m(Task[38;5;241m=[39m[38;5;124m"[39m[38;5;124mThird Year Review[39m[38;5;124m"[39m, Start[38;5;241m=[39m[38;5;124m'[39m[38;5;124m2022-11-01[39m[38;5;124m'[39m, Finish[38;5;241m=[39m[38;5;124m'[39m[38;5;124m2022-12-01[39m[38;5;124m'[39m),
[1;32m     12[0m       [38;5;28mdict[39m(Task[38;5;241m=[39m[38;5;124m"[39m[38;5;124mHPC IO tuner[39m[38;5;124m"[39m, Start[38;5;241m=[39m[38;5;124m'[39m[38;5;124m2022-07-10[39m[38;5;124m'[39m, Finish[38;5;241m=[39m[38;5;124m'[39m[38;5;124m2022-07-30[39m[38;5;124m'[39m),
[1;32m     13[0m       [38;5;28mdict[39m(Task[38;5;241m=[39m[38;5;124m"[39m[38;5;124mSC deadline[39m[38;5;124m"[39m, Start[38;5;241m=[39m[38;5;124m'[39m[38;5;124m2022-08-1[39m[38;5;124m'[39m, Finish[38;5;241m=[39m[38;5;124m'[39m[38;5;124m2022-08-10[39m[38;5;124m'[39m),
[0;32m   (...)[0m
[1;32m     18[0m       [38;5;28mdict[39m(Task[38;5;241m=[39m[38;5;124m"[39m[38;5;124mCIUK 21[39m[38;5;124m"[39m, Start[38;5;241m=[39m[38;5;124m'[39m[38;5;124m2021-10-01[39m[38;5;124m'[39m, Finish[38;5;241m=[39m[38;5;124m'[39m[38;5;124m2021-11-01[39m[38;5;124m'[39m),
[1;32m     19[0m       [38;5;28mdict[39m(Task[38;5;241m=[39m[38;5;124m"[39m[38;5;124mFirst Year Review[39m[38;5;124m"[39m, Start[38;5;241m=[39m[38;5;124m'[39m[38;5;124m2021-1-01[39m[38;5;124m'[39m, Finish[38;5;241m=[39m[38;5;124m'[39m[38;5;124m2021-2-01[39m[38;5;124m'[39m)]
[1;32m     21[0m fig [38;5;241m=[39m ff[38;5;241m.[39mcreate_gantt(df)

[0;31mNameError[0m: name 'figure' is not defined
NameError: name 'figure' is not defined

